// Public entry point for @web10/shared — the ONLY module the app workspaces may
// import from. The package `exports` map in package.json enforces this boundary:
// deep paths (e.g. @web10/shared/src/domain/x) do not resolve.
//
// Everything below is a named domain type, validated API/SSE client, or formatter
// derived VERBATIM from docs/SPEC.md §5/§6 (Milestone FRONTEND, Phase F1).

// Domain enums (schemas + inferred literal types).
export {
  StreamStatusSchema,
  NowPlayingSourceSchema,
  QueueItemSourceSchema,
  QueueItemStatusSchema,
  SuperChatStatusSchema,
  SocialKindSchema,
  OverlayStyleSchema,
  OverlayLayoutSchema,
  BannerTypeSchema,
  BannerStyleSchema,
  BannerPositionSchema,
  PlaybackStateSchema,
  type StreamStatus,
  type NowPlayingSource,
  type QueueItemSource,
  type QueueItemStatus,
  type SuperChatStatus,
  type SocialKind,
  type OverlayStyle,
  type OverlayLayout,
  type BannerType,
  type BannerStyle,
  type BannerPosition,
  type PlaybackState,
} from './domain/enums';

// Player-state DTOs (schemas + inferred types).
export {
  StreamStateSchema,
  NowPlayingSchema,
  QueueItemSchema,
  QueueStateSchema,
  TopDonatorSchema,
  RecentDonationSchema,
  DonationGoalSchema,
  SuperChatMessageSchema,
  SuperChatStateSchema,
  SocialLinkSchema,
  OverlaySettingsSchema,
  BannerSchema,
  PlayerStateSchema,
  type StreamState,
  type NowPlaying,
  type QueueItem,
  type QueueState,
  type TopDonator,
  type RecentDonation,
  type DonationGoal,
  type SuperChatMessage,
  type SuperChatState,
  type SocialLink,
  type OverlaySettings,
  type Banner,
  type PlayerState,
} from './domain/player-state';

// Admin cabinet DTOs (schemas + inferred types).
export {
  AdminSessionSchema,
  LoginAdminRequestSchema,
  EmptyAdminRequestSchema,
  LibraryScanRequestSchema,
  LibraryScanAcceptedSchema,
  LibraryScanStatusSchema,
  AdminTrackSchema,
  AdminTrackPageSchema,
  TrackMetadataUpdateRequestSchema,
  QueueTrackRequestSchema,
  PlayNowRequestSchema,
  QueueTrackAcceptedSchema,
  PlaybackQueueAcceptedSchema,
  QueueReorderRequestSchema,
  ReorderQueueRequestSchema,
  PlaybackCommandSchema,
  StreamNodePlaybackControlSchema,
  PlaybackControlQuerySchema,
  DonationGoalUpdateRequestSchema,
  SocialLinkReplaceItemSchema,
  SocialLinksReplaceRequestSchema,
  BannerReplaceItemSchema,
  BannersReplaceRequestSchema,
  PlaylistTypeSchema,
  PlaylistSourceSchema,
  PlaylistOrderSchema,
  PlaylistScheduleSchema,
  PlaylistSchema,
  PlaylistMutationRequestSchema,
  PlaylistItemSchema,
  PlaylistItemCreateRequestSchema,
  PlaylistItemReplaceRowSchema,
  PlaylistItemsReplaceRequestSchema,
  StorageDefaultBackendSchema,
  StorageAdditionalBackendSchema,
  StorageSchema,
  StorageAdditionalBackendReplaceSchema,
  StorageReplaceRequestSchema,
  StorageCacheSettingsSchema,
  StorageCacheSettingsUpdateSchema,
  StorageEntryKindSchema,
  StorageEntrySchema,
  StorageEntryPageSchema,
  StorageFolderCreateRequestSchema,
  StorageDeleteSelectionSchema,
  StorageDeleteRequestSchema,
  StorageDeleteConfirmRequestSchema,
  StoragePlaylistMembershipSchema,
  StorageImpactTrackSchema,
  StorageCurrentTrackSchema,
  StorageDeleteImpactSchema,
  StorageDeleteResultSchema,
  StreamNodeControlSchema,
  StreamNodeStatusSchema,
  PaidVerticalSliceFixtureRequestSchema,
  PaidVerticalSliceFixtureSchema,
  type AdminSession,
  type LoginAdminRequest,
  type EmptyAdminRequest,
  type LibraryScanRequest,
  type LibraryScanAccepted,
  type LibraryScanStatus,
  type AdminTrack,
  type AdminTrackPage,
  type TrackMetadataUpdateRequest,
  type QueueTrackRequest,
  type PlayNowRequest,
  type QueueTrackAccepted,
  type PlaybackQueueAccepted,
  type QueueReorderRequest,
  type ReorderQueueRequest,
  type PlaybackCommand,
  type StreamNodePlaybackControl,
  type PlaybackControlQuery,
  type DonationGoalUpdateRequest,
  type SocialLinkReplaceItem,
  type SocialLinksReplaceRequest,
  type BannerReplaceItem,
  type BannersReplaceRequest,
  type PlaylistSchedule,
  type PlaylistType,
  type PlaylistSource,
  type PlaylistOrder,
  type Playlist,
  type PlaylistPolicy,
  type PlaylistMutationRequest,
  type PlaylistItem,
  type PlaylistItemCreateRequest,
  type PlaylistItemReplaceRow,
  type PlaylistItemsReplaceRequest,
  type StorageDefaultBackend,
  type StorageAdditionalBackend,
  type Storage,
  type StorageAdditionalBackendReplace,
  type StorageReplaceRequest,
  type StorageCacheSettings,
  type StorageCacheSettingsUpdate,
  type StorageEntryKind,
  type StorageEntry,
  type StorageEntryPage,
  type StorageFolderCreateRequest,
  type StorageDeleteSelection,
  type StorageDeleteRequest,
  type StorageDeleteConfirmRequest,
  type StoragePlaylistMembership,
  type StorageImpactTrack,
  type StorageCurrentTrack,
  type StorageDeleteImpact,
  type StorageDeleteResult,
  type StreamNodeControl,
  type StreamNodeStatus,
  type PaidVerticalSliceFixtureRequest,
  type PaidVerticalSliceFixture,
} from './domain/admin';

// Error contract.
export { ProblemDetailsSchema, type ProblemDetails } from './domain/problem-details';

// HTTP API client.
export {
  API_V0_PREFIX,
  ApiError,
  apiFetch,
  apiSend,
  apiUpload,
  apiRawResponse,
  clearAdminSession,
  getApiBaseUrl,
  setAdminSession,
  setApiBaseUrl,
  subscribeToAdminSessionInvalidation,
  type FetchImpl,
  type RequestOptions,
  type ApiRequest,
  type SendRequest,
  type UploadRequest,
  type RawRequest,
} from './api/client';
export { getPlayerState, playerStreamUrl } from './api/player';
export {
  loginAdmin,
  getAdminSession,
  logoutAdmin,
  createLibraryScan,
  getLibraryScan,
  getTracksPage,
  updateTrackMetadata,
  replaceTrackCover,
  removeTrackCover,
  queueTrack,
  reorderQueue,
  removeQueueItem,
  skipCurrent,
  restartCurrent,
  playNow,
  getDonationGoal,
  updateDonationGoal,
  getSocialLinks,
  replaceSocialLinks,
  getBanners,
  replaceBanners,
  getPlaylists,
  createPlaylist,
  replacePlaylist,
  getStorageEntries,
  storageContentUrl,
  uploadStorageFile,
  createStorageFolder,
  previewStorageDelete,
  deleteStorageEntries,
  type StorageEntriesQuery,
  type StorageContentQuery,
  getPlaylistItems,
  createPlaylistItem,
  replacePlaylistItems,
  getStorage,
  replaceStorage,
  getStorageCacheSettings,
  updateStorageCacheSettings,
  getStreamNodeStatus,
  startStreamNode,
  pauseStreamNode,
  stopStreamNode,
  restartStreamNode,
  createPaidVerticalSliceFixture,
  type TracksQuery,
  type CoverUploadBody,
} from './api/admin';

// SSE client + fallback.
export {
  PLAYER_EVENT_NAMES,
  type PlayerEventName,
  type PlayerEventPayloads,
} from './sse/events';
export {
  createPlayerEventsClient,
  type PlayerEventsClient,
  type PlayerEventHandlers,
  type PlayerEventsOptions,
  type PlayerEventsTransport,
  type SseConnection,
  type SseConnector,
  type SseConnectorSpec,
} from './sse/client';

// Formatters.
export { formatStars } from './format/stars';
export { formatUtcTime, INVALID_TIME_PLACEHOLDER } from './format/time';
export { formatDuration, formatProgress, formatTrackLabel } from './format/track';
